### ISSUE TITLE
Does not adhere to README template

### ISSUE THREAD

**Issue by schuemie** [ohdsi-studies/IntraVitrealCx#4]
Please adhere **exactly** to the [README template](https://github.com/ohdsi-studies/StudyRepoTemplate/blob/master/templateREADME.md). Otherwise, I can't parse it.

**Comment by chandryou** [comment]
@schuemie 
Does [this](https://github.com/ohdsi-studies/IntraVitrealCx/commit/4b27524a375a49e9cb80fb8994965cebd0c34c74) seem alright?

**Comment by schuemie** [comment]
Almost! I took the liberty of making the minor edits that were required. Feel free to change of course.

**Comment by chandryou** [comment]
@schumie, does ‘almost’ mean ‘okay’? Otherwise, plz feel free to edit and close this issue :)

**Comment by schuemie** [comment]
I meant that now that I've edited it, it does match my requirements. However, please check if you're ok with my changes. Specifically, I added your forums tag, but could also be another person's tag.
